server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.myapp.hellotest.controller
    title: ctg-myapp-hellotest RESTful APIs
    description: ctg-myapp-hellotest RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.myapp.hellotest.controller
        title: actg-myapp-hellotest Open APIs
        description: ctg-myapp-hellotest Open API
        version: 1.0.0-SNAPSHOT
